In [126]:
import numpy as np
import numpy.matrixlib

In [3]:
s = np.asarray([
[25,52,29,88,38,86,39,26,80,47],
[71,73,88,35,25,69,84,45,59,87],
[42,46,71,77,69,56,79,59,45,52],
[63,60,41,61,46,51,57,79,72,68],
[49,37,68,45,71,42,32,56,43,64],
[23,29,34,89,39,49,24,78,66,83],
[64,60,47,32,70,80,43,43,52,59],
[75,81,40,69,25,82,84,47,69,27],
[20,70,56,31,61,76,35,67,25,45],
[83,75,47,58,40,23,73,52,70,86]
])

In [19]:
s

array([[25, 52, 29, 88, 38, 86, 39, 26, 80, 47],
       [71, 73, 88, 35, 25, 69, 84, 45, 59, 87],
       [42, 46, 71, 77, 69, 56, 79, 59, 45, 52],
       [63, 60, 41, 61, 46, 51, 57, 79, 72, 68],
       [49, 37, 68, 45, 71, 42, 32, 56, 43, 64],
       [23, 29, 34, 89, 39, 49, 24, 78, 66, 83],
       [64, 60, 47, 32, 70, 80, 43, 43, 52, 59],
       [75, 81, 40, 69, 25, 82, 84, 47, 69, 27],
       [20, 70, 56, 31, 61, 76, 35, 67, 25, 45],
       [83, 75, 47, 58, 40, 23, 73, 52, 70, 86]])

In [6]:
A = s - np.asarray([2,6,8,8,3,5,5,7,4,9])
A

array([[23, 46, 21, 80, 35, 81, 34, 19, 76, 38],
       [69, 67, 80, 27, 22, 64, 79, 38, 55, 78],
       [40, 40, 63, 69, 66, 51, 74, 52, 41, 43],
       [61, 54, 33, 53, 43, 46, 52, 72, 68, 59],
       [47, 31, 60, 37, 68, 37, 27, 49, 39, 55],
       [21, 23, 26, 81, 36, 44, 19, 71, 62, 74],
       [62, 54, 39, 24, 67, 75, 38, 36, 48, 50],
       [73, 75, 32, 61, 22, 77, 79, 40, 65, 18],
       [18, 64, 48, 23, 58, 71, 30, 60, 21, 36],
       [81, 69, 39, 50, 37, 18, 68, 45, 66, 77]])

In [157]:
g = np.matrix(A).T * np.asarray([[16,20,8, 2, 10, 63, 1, 17, 14, 22]]).T

g

matrix([[ 7320],
        [ 8006],
        [ 6857],
        [10434],
        [ 6629],
        [ 8992],
        [ 7584],
        [ 9133],
        [ 9975],
        [10396]])

In [96]:
res = np.asarray([[26, 12, 17, 10, 40, 37, 37, 52, 59, 37]])-np.asarray([2,6,8,8,3,5,5,7,4,9])
res

array([[24,  6,  9,  2, 37, 32, 32, 45, 55, 28]])

In [87]:
sol = np.vstack((A,np.asarray([[64, 64, 64, 64, 64, 64, 64, 64, 64, 64]]),res))
sol

array([[23, 46, 21, 80, 35, 81, 34, 19, 76, 38],
       [69, 67, 80, 27, 22, 64, 79, 38, 55, 78],
       [40, 40, 63, 69, 66, 51, 74, 52, 41, 43],
       [61, 54, 33, 53, 43, 46, 52, 72, 68, 59],
       [47, 31, 60, 37, 68, 37, 27, 49, 39, 55],
       [21, 23, 26, 81, 36, 44, 19, 71, 62, 74],
       [62, 54, 39, 24, 67, 75, 38, 36, 48, 50],
       [73, 75, 32, 61, 22, 77, 79, 40, 65, 18],
       [18, 64, 48, 23, 58, 71, 30, 60, 21, 36],
       [81, 69, 39, 50, 37, 18, 68, 45, 66, 77],
       [64, 64, 64, 64, 64, 64, 64, 64, 64, 64],
       [24,  6,  9,  2, 37, 32, 32, 45, 55, 28]])

In [88]:
S = np.matrix(sol.T)

In [89]:
S

matrix([[23, 69, 40, 61, 47, 21, 62, 73, 18, 81, 64, 24],
        [46, 67, 40, 54, 31, 23, 54, 75, 64, 69, 64,  6],
        [21, 80, 63, 33, 60, 26, 39, 32, 48, 39, 64,  9],
        [80, 27, 69, 53, 37, 81, 24, 61, 23, 50, 64,  2],
        [35, 22, 66, 43, 68, 36, 67, 22, 58, 37, 64, 37],
        [81, 64, 51, 46, 37, 44, 75, 77, 71, 18, 64, 32],
        [34, 79, 74, 52, 27, 19, 38, 79, 30, 68, 64, 32],
        [19, 38, 52, 72, 49, 71, 36, 40, 60, 45, 64, 45],
        [76, 55, 41, 68, 39, 62, 48, 65, 21, 66, 64, 55],
        [38, 78, 43, 59, 55, 74, 50, 18, 36, 77, 64, 28]])

In [90]:
import sympy

In [91]:
sympy.Matrix(S).rref()

(Matrix([
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0,   3223585386717184/37486410700520489,    26554818219439376/37486410700520489],
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0,  7789806131569856/112459232101561467,   39382330405348252/112459232101561467],
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0,   6097218628108800/37486410700520489,    21864881480382792/37486410700520489],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 12624624409176064/112459232101561467,  398323373405194550/112459232101561467],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0,  16705835710445120/37486410700520489,   -28293908536550758/37486410700520489],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0,  2927099250233728/112459232101561467, -153073744123573627/112459232101561467],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, -7961833319839424/112459232101561467,   36668192901001403/112459232101561467],
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0,   6854385671948608/37486410700520489,   -56794439400334599/37486410700520489],
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 16368810055458176/112459232101561467,  -63632710139903558/112459232101

In [94]:
112459232101561467 % 255

162

In [95]:
39382330405348252 % 255

142

In [115]:
154,76,209,202,232,37,165,180,251,165

(154, 76, 209, 202, 232, 37, 165, 180, 251, 165)

In [119]:
target = np.asarray([[9,51,17,21,15,34,21,41,42,40]]) - np.asarray([[2,6,8,8,3,5,5,7,4,9]])
target

array([[ 7, 45,  9, 13, 12, 29, 16, 34, 38, 31]])

In [117]:
target.shape

(1, 10)

In [128]:
P=np.matrix(A).T
P

matrix([[23, 69, 40, 61, 47, 21, 62, 73, 18, 81],
        [46, 67, 40, 54, 31, 23, 54, 75, 64, 69],
        [21, 80, 63, 33, 60, 26, 39, 32, 48, 39],
        [80, 27, 69, 53, 37, 81, 24, 61, 23, 50],
        [35, 22, 66, 43, 68, 36, 67, 22, 58, 37],
        [81, 64, 51, 46, 37, 44, 75, 77, 71, 18],
        [34, 79, 74, 52, 27, 19, 38, 79, 30, 68],
        [19, 38, 52, 72, 49, 71, 36, 40, 60, 45],
        [76, 55, 41, 68, 39, 62, 48, 65, 21, 66],
        [38, 78, 43, 59, 55, 74, 50, 18, 36, 77]])

In [159]:
#print("A:",np.sum(np.linalg.inv(P)*(g % 64 + 64 * i) % 1))

from sympy import Matrix, pprint


In [160]:
A_sp = Matrix(P)
A_sp

Matrix([
[23, 69, 40, 61, 47, 21, 62, 73, 18, 81],
[46, 67, 40, 54, 31, 23, 54, 75, 64, 69],
[21, 80, 63, 33, 60, 26, 39, 32, 48, 39],
[80, 27, 69, 53, 37, 81, 24, 61, 23, 50],
[35, 22, 66, 43, 68, 36, 67, 22, 58, 37],
[81, 64, 51, 46, 37, 44, 75, 77, 71, 18],
[34, 79, 74, 52, 27, 19, 38, 79, 30, 68],
[19, 38, 52, 72, 49, 71, 36, 40, 60, 45],
[76, 55, 41, 68, 39, 62, 48, 65, 21, 66],
[38, 78, 43, 59, 55, 74, 50, 18, 36, 77]])

In [163]:
A_inv = A_sp.inv_mod(64)
A_inv

Matrix([
[ 2,  0, 29, 41, 27, 26, 14,  3, 25, 25],
[17, 20,  3, 63, 24, 55, 31, 53, 26, 37],
[34, 38, 25, 22, 11, 52, 12, 16,  8, 46],
[57, 43, 25, 19, 11, 10, 60, 51, 57, 19],
[17, 56, 32, 49,  2, 10, 47, 53, 51, 52],
[45, 29, 57, 32, 15, 54, 44, 11, 30, 53],
[15, 34, 22,  4, 57, 32, 53, 48, 62, 24],
[61, 41,  4, 22,  9, 37, 41, 35, 17, 18],
[45, 29, 32, 40, 36, 52, 19, 49, 53, 31],
[24, 61, 52, 18,  4, 28, 13, 28,  0, 12]])

In [221]:
ans_s = (A_inv * Matrix((target-bias).T)).T

In [222]:
ans = (np.asarray(ans_s.tolist(),dtype=np.int).T % 64 ).flatten()
ans

array([43, 62, 48, 53, 45, 33, 62, 53, 52, 49])

In [223]:
mp = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"

In [224]:
for i in ans:
    print(mp[i], end="")

r-w1th-10x

SyntaxError: invalid token (<ipython-input-219-c179188ea03a>, line 1)

In [220]:
bias = np.asarray([[2,6,8,8,3,5,5,7,4,9]])

In [229]:
target = np.asarray([[9,51,17,21,15,34,21,41,42,40]])
ans_s = (A_inv * Matrix((target-bias).T)).T
ans = (np.asarray(ans_s.tolist(),dtype=np.int).T % 64 ).flatten()
mp = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
for i in ans:
    print(mp[i], end="")

h1ll-c1ph3

In [231]:
target = np.asarray([[56,34,3,12,60,28,30,37,50,46]])
ans_s = (A_inv * Matrix((target-bias).T)).T
ans = (np.asarray(ans_s.tolist(),dtype=np.int).T % 64 ).flatten()
mp = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
for i in ans:
    print(mp[i], end="")

r-w1th-10x

In [228]:
target = np.matrix([[30,8,44,56,31,31,56,3,10,30]])
ans_s = (A_inv * Matrix((target-bias).T)).T
ans = (np.asarray(ans_s.tolist(),dtype=np.int).T % 64 ).flatten()
mp = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
for i in ans:
    print(mp[i], end="")

10-r3v3rs1

In [230]:
target = np.asarray([[6,55,4,12,10,34,33,51,46,7]])
ans_s = (A_inv * Matrix((target-bias).T)).T
ans = (np.asarray(ans_s.tolist(),dtype=np.int).T % 64 ).flatten()
mp = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
for i in ans:
    print(mp[i], end="")

bl3-matr1x